// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLsK_Q5a-twOUwZAjwIpzjnKhq6Ja5pPM',
    appId: '1:567335629179:web:5c63dd98daa020d9c34dde',
    messagingSenderId: '567335629179',
    projectId: 'randomproject2004',
    authDomain: 'randomproject2004.firebaseapp.com',
    storageBucket: 'randomproject2004.appspot.com',
    measurementId: 'G-C2ZXP29D0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCgmALsGm524Ubzb5Ec2r_GdNMHCuZ5V0',
    appId: '1:567335629179:android:de8989e006823488c34dde',
    messagingSenderId: '567335629179',
    projectId: 'randomproject2004',
    storageBucket: 'randomproject2004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVAJoFb2yicJ6YO5r3cYPyVYtidFFUEks',
    appId: '1:567335629179:ios:08dd1e2922d30453c34dde',
    messagingSenderId: '567335629179',
    projectId: 'randomproject2004',
    storageBucket: 'randomproject2004.appspot.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVAJoFb2yicJ6YO5r3cYPyVYtidFFUEks',
    appId: '1:567335629179:ios:08dd1e2922d30453c34dde',
    messagingSenderId: '567335629179',
    projectId: 'randomproject2004',
    storageBucket: 'randomproject2004.appspot.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLsK_Q5a-twOUwZAjwIpzjnKhq6Ja5pPM',
    appId: '1:567335629179:web:fc6f854ee871a8fac34dde',
    messagingSenderId: '567335629179',
    projectId: 'randomproject2004',
    authDomain: 'randomproject2004.firebaseapp.com',
    storageBucket: 'randomproject2004.appspot.com',
    measurementId: 'G-24CJ3MGFVE',
  );
}
